version: '3'

services:
  druid-zookeeper:
    stdin_open: true
    tty: true
    build: .
    image: gcr.io/zenatix-data-archiver/druid:latest
    container_name: druid-zookeeper
    user: daemon
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    entrypoint: ["bash", "-c", "/usr/local/zookeeper/bin/zkServer.sh start-foreground"]
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_ZOOKEEPER_IP}

  druid-mysql:
    stdin_open: true
    tty: true
    image: gcr.io/zenatix-data-archiver/druid:latest
    container_name: druid-mysql
    user: mysql
    entrypoint: ["bash", "-c", "/usr/bin/pidproxy /var/run/mysqld/mysqld.pid /usr/bin/mysqld_safe"]
    ports:
      - "3306:3306"
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_MYSQL_IP}

  druid-coordinator:
    stdin_open: true
    tty: true
    image: gcr.io/zenatix-data-archiver/druid:latest
    container_name: druid-coordinator
    user: druid
    entrypoint: ["bash", "-c", "java -server -Xmx1g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Ddruid.host=%(${DRUID_COORDINATOR_IP})s -Ddruid.extensions.loadList=[\"mysql-metadata-storage\"] -Ddruid.extensions.directory=/usr/local/druid/extensions -Ddruid.extensions.hadoopDependenciesDir=/usr/local/druid/hadoop-dependencies -Ddruid.metadata.storage.type=mysql -Ddruid.metadata.storage.connector.connectURI=jdbc:mysql://${DRUID_MYSQL_IP}:3306/druid -Ddruid.metadata.storage.connector.user=druid -Ddruid.metadata.storage.connector.password=diurd -Ddruid.coordinator.asOverlord.enabled=true -Ddruid.coordinator.asOverlord.overlordService=druid/overlord -Ddruid.indexer.fork.property.druid.processing.numThreads=1 -Ddruid.indexer.storage.type=metadata -Ddruid.indexer.queue.startDelay=PT0M -Ddruid.indexer.runner.javaOpts=\"-server -Xmx1g -XX:MaxDirectMemorySize=2147483648\" -Ddruid.processing.buffer.sizeBytes=536870912 -Ddruid.coordinator.startDelay=PT5S -cp /usr/local/druid/lib/* io.druid.cli.Main server coordinator"]
    ports:
      - "8081:8081"
      - "8090:8090"
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_COORDINATOR_IP}

  druid-historical:
    stdin_open: true
    tty: true
    image: gcr.io/zenatix-data-archiver/druid:latest
    container_name: druid-historical
    user: druid
    entrypoint: ["bash", "-c", "java -server -Xmx1g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Ddruid.host=%(${DRUID_HISTORICAL_IP})s -Ddruid.extensions.loadList=[\"druid-s3-extensions\"] -Ddruid.extensions.directory=/usr/local/druid/extensions -Ddruid.extensions.hadoopDependenciesDir=/usr/local/druid/hadoop-dependencies -Ddruid.s3.accessKey=AKIAIMKECRUYKDQGR6YQ -Ddruid.s3.secretKey=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 -Ddruid.computation.buffer.size=67108864 -Ddruid.segmentCache.locations=\"[{\"path\":\"/var/tmp/druid/indexCache\",\"maxSize\":5000000000}]\" -Ddruid.server.maxSize=5000000000 -cp /usr/local/druid/lib/* io.druid.cli.Main server historical"] 
    ports:
      - "8083:8083"
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_HISTORICAL_IP}

  druid-broker:
    stdin_open: true
    tty: true
    image: gcr.io/zenatix-data-archiver/druid:latest
    container_name: druid-broker
    user: druid
    entrypoint: ["bash", "-c", "java -server -Xmx1g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Ddruid.host=%(${DRUID_BROKER_IP})s -Ddruid.computation.buffer.size=67108864 -Ddruid.broker.cache.sizeInBytes=33554432 -cp /usr/local/druid/lib/* io.druid.cli.Main server broker"] 
    ports:
      - "8082:8082"
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_BROKER_IP}

  
networks:
    zenatix-docker:
        external:
            name: zenatix-docker