version: '3'

services:
  druid-zookeeper:
    stdin_open: true
    tty: true
    build: .
    image: zenatix/druid:latest
    container_name: druid-zookeeper
    volumes:
      - ./conf:/druid/conf
    ports:
      - "2181:2181"
    depends_on:
      - druid-postgresql
    entrypoint: ["bash", "-c", "bin/run-zk /druid/conf"]
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_ZOOKEEPER_IP}

  druid-coordinator:
    stdin_open: true
    tty: true
    image: zenatix/druid:latest
    container_name: druid-coordinator
    volumes:
      - ./conf:/druid/conf
      - druid-volume:/var/druid
      - ./data:/var/druid/data
    ports:
      - "8081:8081"
    entrypoint: ["bash", "-c", "bin/run-druid coordinator /druid/conf"]
    depends_on:
      - druid-zookeeper
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_COORDINATOR_IP}

  druid-overlord:
    stdin_open: true
    tty: true
    image: zenatix/druid:latest
    container_name: druid-overlord
    volumes:
      - ./conf:/druid/conf
      - druid-volume:/var/druid
      - ./data:/var/druid/data
    ports:
      - "8090:8090"
    entrypoint: ["bash", "-c", "bin/run-druid overlord /druid/conf"]
    depends_on:
      - druid-historical
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_OVERLORD_IP}

  druid-middlemanager:
    stdin_open: true
    tty: true
    image: zenatix/druid:latest
    container_name: druid-middlemanager
    volumes:
      - ./conf:/druid/conf
      - druid-volume:/var/druid
      - ./data:/var/druid/data
    ports:
      - "8091:8091"
    entrypoint: ["bash", "-c", "bin/run-druid middleManager /druid/conf"]
    depends_on:
      - druid-overlord
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_MIDDLEMANAGER_IP}

  druid-historical:
    stdin_open: true
    tty: true
    image: zenatix/druid:latest
    container_name: druid-historical
    entrypoint: ["bash", "-c", "bin/run-druid historical /druid/conf"] 
    depends_on:
      - druid-router
    ports:
      - "8083:8083"
    volumes:
      - ./conf:/druid/conf
      - druid-volume:/var/druid
      - ./data:/var/druid/data
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_HISTORICAL_IP}
  druid-broker:
    stdin_open: true
    tty: true
    image: zenatix/druid:latest
    container_name: druid-broker
    volumes:
      - ./conf:/druid/conf
      - druid-volume:/var/druid
      - ./data:/var/druid/data
    entrypoint: ["bash", "-c", "bin/run-druid broker /druid/conf"]
    depends_on:
      - druid-coordinator
    ports:
      - "8082:8082"
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_BROKER_IP}

  druid-router:
    stdin_open: true
    tty: true
    image: zenatix/druid:latest
    container_name: druid-router
    volumes:
      - ./conf:/druid/conf
    entrypoint: ["bash", "-c", "bin/run-druid router /druid/conf"]
    depends_on:
      - druid-broker
    ports:
      - "8888:8888"
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_ROUTER_IP}

  druid-postgresql:
    stdin_open: true
    tty: true
    image: library/postgres:latest
    container_name: druid-postgresql
    environment:
      - POSTGRES_USER=druid
      - POSTGRES_PASSWORD=diurd
      - POSTGRES_DB=druid
    ports:
      - "5436:5432"
    volumes:
        - postgresql-druid-volume:/var/lib/postgresql/data
    networks:
        zenatix-docker:
            ipv4_address: ${DRUID_POSTGRESQL_IP}
  
networks:
    zenatix-docker:
        external:
            name: zenatix-docker

volumes:
    postgresql-druid-volume:
        external: true
    druid-volume:
        external: true
